
version: 2

models:
  - name: carpark_occupancy
    description: "Car park occupancy dbt model"
    columns:
      - name: timestamp
        tests:
          - not_null

  - name: carpark_duration
    description: "Car park duration dbt model"
    columns:
      - name: timestamp
        tests:
          - not_null

  - name: carpark_utilisation
    description: "Car park utilisation dbt model"
    columns:
      - name: timestamp
        tests:
          - not_null
