
version: 2

models:
  - name: carpark_occupancy
    description: "Car park occupancy model"
    columns:
      - name: timestamp
        tests:
          - not_null

  - name: carpark_duration
    description: "Car park duration model"
    columns:
      - name: timestamp
        tests:
          - not_null

  - name: carpark_utilisation
    description: "Car park utilisation model"
    columns:
      - name: timestamp
        tests:
          - not_null
  - name: carpark_floor_utilisation
    description: "Car park floor utilisation model"
    columns:
      - name: timestamp
        tests:
          - not_null
  - name: carpark_area_utilisation
    description: "Car park area utilisation model"
    columns:
      - name: timestamp
        tests:
          - not_null
