
version: 2

models:
  - name: carpark_occupancy
    description: "A starter dbt model"
    columns:
      - name: timestamp
        tests:
          - not_null

  - name: carpark_duration
    description: "A starter dbt model"
    columns:
      - name: timestamp
        tests:
          - not_null

  - name: carpark_utilization
    description: "A starter dbt model"
    columns:
      - name: timestamp
        tests:
          - not_null
