version: 2

models:
  - name: equipment_events
    description: "Transformed equipment events"
    columns:
      - name: timestamp
        tests:
          - not_null
  - name: events_error
    description: "Transformed equipment events as error events"
    columns:
      - name: datetime
        tests:
          - not_null
